[package]
name = "dvc"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.39.0"
features = [
    "implement",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_RemoteDesktop",
]
