# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-case-conflict" },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [
  { id = "actionlint" },
]

[[repos]]
repo = "https://github.com/doublify/pre-commit-rust"
rev = "v1.0"
hooks = [
  { id = "fmt" },
  { id = "clippy" },
]
