[package]
name = "dvc_inproc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dvc_core = { path = "../core" }

[dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Foundation",
]
