[package]
name = "rd_pipe-inproc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rd_pipe-core = { path = "../core" }
tracing = "0.1"
tracing-appender = "0.2"

[dependencies.windows]
version = "0.39"
features = [
    "Win32_Foundation",
]
