name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: cargo fmt -- --check
        run: cargo fmt --all -- --check
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: i686-pc-windows-msvc
            suffix: x86
          - target: x86_64-pc-windows-msvc
            suffix: x64
          - target: aarch64-pc-windows-msvc
            suffix: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Build target
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rd_pipe-${{ matrix.suffix }}
          compression-level: 9
          path: |
            ./target/${{ matrix.target }}/release/*.dll*
            ./target/${{ matrix.target }}/release/*.pdb
